### ISSUE TITLE
Не работает поиск пользователя

### ISSUE THREAD

**Issue by disovi** [Medrenguard/vk-vue#1]
![image](https://user-images.githubusercontent.com/705617/172380570-c69309df-2881-42d4-98ff-0821bb04acde.png)

**Comment by Medrenguard** [comment]
Починено, сделал обход CORS с помощью JSONP
На dev-среде CORS обходилась локальным плагином в браузере

**Comment by disovi** [comment]
![image](https://user-images.githubusercontent.com/705617/172862203-92a658dd-22c3-4ba3-ba12-ce3b8831742c.png)

@Medrenguard теперь другая ошибка

**Comment by Medrenguard** [comment]
Понимаю, из каких строчек эта ошибка, но из-за чего она воспроизводится — не понимаю.
Саму ошибку воспроизвести не получилось.

Добавил обработку ошибок от API VK, сейчас лог должен быть более корректный, @disovi посмотришь?
 
Видео самого функционала: [https://youtu.be/mlEf1I39lH0 ](https://youtu.be/mlEf1I39lH0)
Upd: обновил ссылку

**Comment by disovi** [comment]
<img width="747" alt="image" src="https://user-images.githubusercontent.com/705617/173069724-49f2ad98-197c-441e-aa52-06564e587267.png">

@Medrenguard

**Comment by Medrenguard** [comment]
@disovi обновил ключ, проверил под другими ip, все работает
